name: lint and build
on: [push]
jobs:
  lint:
    name: checks lint
    runs-on: ubuntu-22.04
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: run lint on server
        run: |
          cd server
          pnpm run lint
      
  
